name: main_app
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../packages/core
  feature_home:
    path: ../../packages/feature_home
  shared_ui:
    path: ../../packages/shared_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
